# Generated by Django 2.1.7 on 2019-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20190219_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='associated_post',
            field=models.ManyToManyField(to='reddit.RedditPost'),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='keywords_generated',
            field=models.BooleanField(default=False),
        ),
    ]
