# Generated by Django 2.1.7 on 2019-02-20 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20190220_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditpost',
            old_name='subreddit_prefix',
            new_name='subreddit',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
